/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Action : The action that will be executed.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Action {
    /// The type of the action.
    #[serde(rename = "action_type", skip_serializing_if = "Option::is_none")]
    pub action_type: Option<ActionType>,
}

impl Action {
    /// The action that will be executed.
    pub fn new() -> Action {
        Action {
            action_type: None,
        }
    }
}

/// The type of the action.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ActionType {
    #[serde(rename = "EmailContacts")]
    EmailContacts,
    #[serde(rename = "AutoRenew")]
    AutoRenew,
}

