/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AdministratorDetails : Details of the organization administrator of the certificate issuer.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdministratorDetails {
    /// First name.
    #[serde(rename = "first_name", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    /// Last name.
    #[serde(rename = "last_name", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    /// Email address.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Phone number.
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
}

impl AdministratorDetails {
    /// Details of the organization administrator of the certificate issuer.
    pub fn new() -> AdministratorDetails {
        AdministratorDetails {
            first_name: None,
            last_name: None,
            email: None,
            phone: None,
        }
    }
}


