/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Attributes : The object attributes managed by the KeyVault service.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Attributes {
    /// Determines whether the object is enabled.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Not before date in UTC.
    #[serde(rename = "nbf", skip_serializing_if = "Option::is_none")]
    pub nbf: Option<i32>,
    /// Expiry date in UTC.
    #[serde(rename = "exp", skip_serializing_if = "Option::is_none")]
    pub exp: Option<i32>,
    /// Creation time in UTC.
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<i32>,
    /// Last updated time in UTC.
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<i32>,
}

impl Attributes {
    /// The object attributes managed by the KeyVault service.
    pub fn new() -> Attributes {
        Attributes {
            enabled: None,
            nbf: None,
            exp: None,
            created: None,
            updated: None,
        }
    }
}


