/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CertificateOperationUpdateParameter : The certificate operation update parameters.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CertificateOperationUpdateParameter {
    /// Indicates if cancellation was requested on the certificate operation.
    #[serde(rename = "cancellation_requested")]
    pub cancellation_requested: bool,
}

impl CertificateOperationUpdateParameter {
    /// The certificate operation update parameters.
    pub fn new(cancellation_requested: bool) -> CertificateOperationUpdateParameter {
        CertificateOperationUpdateParameter {
            cancellation_requested,
        }
    }
}


