/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CertificateIssuerUpdateParameters : The certificate issuer update parameters.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CertificateIssuerUpdateParameters {
    /// The issuer provider.
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    #[serde(rename = "credentials", skip_serializing_if = "Option::is_none")]
    pub credentials: Option<Box<crate::models::IssuerCredentials>>,
    #[serde(rename = "org_details", skip_serializing_if = "Option::is_none")]
    pub org_details: Option<Box<crate::models::OrganizationDetails>>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::IssuerAttributes>>,
}

impl CertificateIssuerUpdateParameters {
    /// The certificate issuer update parameters.
    pub fn new() -> CertificateIssuerUpdateParameters {
        CertificateIssuerUpdateParameters {
            provider: None,
            credentials: None,
            org_details: None,
            attributes: None,
        }
    }
}


