/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CertificateInfoObject {
    /// Certificates needed from customer
    #[serde(rename = "certificates")]
    pub certificates: Vec<crate::models::SecurityDomainCertificateItem>,
    /// Customer to specify the number of certificates (minimum 2 and maximum 10) to restore Security Domain
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<i32>,
}

impl CertificateInfoObject {
    pub fn new(certificates: Vec<crate::models::SecurityDomainCertificateItem>) -> CertificateInfoObject {
        CertificateInfoObject {
            certificates,
            required: None,
        }
    }
}


