/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CertificateIssuerItem : The certificate issuer item containing certificate issuer metadata.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CertificateIssuerItem {
    /// Certificate Identifier.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The issuer provider.
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
}

impl CertificateIssuerItem {
    /// The certificate issuer item containing certificate issuer metadata.
    pub fn new() -> CertificateIssuerItem {
        CertificateIssuerItem {
            id: None,
            provider: None,
        }
    }
}


