/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CertificateMergeParameters : The certificate merge parameters



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CertificateMergeParameters {
    /// The certificate or the certificate chain to merge.
    #[serde(rename = "x5c")]
    pub x5c: Vec<String>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::CertificateAttributes>>,
    /// Application specific metadata in the form of key-value pairs.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<::std::collections::HashMap<String, String>>,
}

impl CertificateMergeParameters {
    /// The certificate merge parameters
    pub fn new(x5c: Vec<String>) -> CertificateMergeParameters {
        CertificateMergeParameters {
            x5c,
            attributes: None,
            tags: None,
        }
    }
}


