/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CertificateIssuerSetParameters : The certificate issuer set parameters.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CertificateIssuerSetParameters {
    /// The issuer provider.
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "credentials", skip_serializing_if = "Option::is_none")]
    pub credentials: Option<Box<crate::models::IssuerCredentials>>,
    #[serde(rename = "org_details", skip_serializing_if = "Option::is_none")]
    pub org_details: Option<Box<crate::models::OrganizationDetails>>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::IssuerAttributes>>,
}

impl CertificateIssuerSetParameters {
    /// The certificate issuer set parameters.
    pub fn new(provider: String) -> CertificateIssuerSetParameters {
        CertificateIssuerSetParameters {
            provider,
            credentials: None,
            org_details: None,
            attributes: None,
        }
    }
}


