/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Contacts : The contacts for the vault certificates.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Contacts {
    /// Identifier for the contacts collection.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The contact list for the vault certificates.
    #[serde(rename = "contacts", skip_serializing_if = "Option::is_none")]
    pub contacts: Option<Vec<crate::models::Contact>>,
}

impl Contacts {
    /// The contacts for the vault certificates.
    pub fn new() -> Contacts {
        Contacts {
            id: None,
            contacts: None,
        }
    }
}


