/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DeletedSecretBundle : A Deleted Secret consisting of its previous id, attributes and its tags, as well as information on when it will be purged.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeletedSecretBundle {
    /// The url of the recovery object, used to identify and recover the deleted secret.
    #[serde(rename = "recoveryId", skip_serializing_if = "Option::is_none")]
    pub recovery_id: Option<String>,
    /// The time when the secret is scheduled to be purged, in UTC
    #[serde(rename = "scheduledPurgeDate", skip_serializing_if = "Option::is_none")]
    pub scheduled_purge_date: Option<i32>,
    /// The time when the secret was deleted, in UTC
    #[serde(rename = "deletedDate", skip_serializing_if = "Option::is_none")]
    pub deleted_date: Option<i32>,
    /// The secret value.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// The secret id.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The content type of the secret.
    #[serde(rename = "contentType", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::SecretAttributes>>,
    /// Application specific metadata in the form of key-value pairs.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<::std::collections::HashMap<String, String>>,
    /// If this is a secret backing a KV certificate, then this field specifies the corresponding key backing the KV certificate.
    #[serde(rename = "kid", skip_serializing_if = "Option::is_none")]
    pub kid: Option<String>,
    /// True if the secret's lifetime is managed by key vault. If this is a secret backing a certificate, then managed will be true.
    #[serde(rename = "managed", skip_serializing_if = "Option::is_none")]
    pub managed: Option<bool>,
}

impl DeletedSecretBundle {
    /// A Deleted Secret consisting of its previous id, attributes and its tags, as well as information on when it will be purged.
    pub fn new() -> DeletedSecretBundle {
        DeletedSecretBundle {
            recovery_id: None,
            scheduled_purge_date: None,
            deleted_date: None,
            value: None,
            id: None,
            content_type: None,
            attributes: None,
            tags: None,
            kid: None,
            managed: None,
        }
    }
}


