/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Error : The key vault server error.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Error {
    /// The error code.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// The error message.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "innererror", skip_serializing_if = "Option::is_none")]
    pub innererror: Option<Box<crate::models::Error>>,
}

impl Error {
    /// The key vault server error.
    pub fn new() -> Error {
        Error {
            code: None,
            message: None,
            innererror: None,
        }
    }
}


