/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FullBackupOperation : Full backup operation



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FullBackupOperation {
    /// Status of the backup operation.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// The status details of backup operation.
    #[serde(rename = "statusDetails", skip_serializing_if = "Option::is_none")]
    pub status_details: Option<String>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<crate::models::Error>>,
    /// The start time of the backup operation in UTC
    #[serde(rename = "startTime", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<i32>,
    /// The end time of the backup operation in UTC
    #[serde(rename = "endTime", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<i32>,
    /// Identifier for the full backup operation.
    #[serde(rename = "jobId", skip_serializing_if = "Option::is_none")]
    pub job_id: Option<String>,
    /// The Azure blob storage container Uri which contains the full backup
    #[serde(rename = "azureStorageBlobContainerUri", skip_serializing_if = "Option::is_none")]
    pub azure_storage_blob_container_uri: Option<String>,
}

impl FullBackupOperation {
    /// Full backup operation
    pub fn new() -> FullBackupOperation {
        FullBackupOperation {
            status: None,
            status_details: None,
            error: None,
            start_time: None,
            end_time: None,
            job_id: None,
            azure_storage_blob_container_uri: None,
        }
    }
}


