/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IssuerBundle : The issuer for Key Vault certificate.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssuerBundle {
    /// Identifier for the issuer object.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The issuer provider.
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    #[serde(rename = "credentials", skip_serializing_if = "Option::is_none")]
    pub credentials: Option<Box<crate::models::IssuerCredentials>>,
    #[serde(rename = "org_details", skip_serializing_if = "Option::is_none")]
    pub org_details: Option<Box<crate::models::OrganizationDetails>>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::IssuerAttributes>>,
}

impl IssuerBundle {
    /// The issuer for Key Vault certificate.
    pub fn new() -> IssuerBundle {
        IssuerBundle {
            id: None,
            provider: None,
            credentials: None,
            org_details: None,
            attributes: None,
        }
    }
}


