/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IssuerParameters : Parameters for the issuer of the X509 component of a certificate.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssuerParameters {
    /// Name of the referenced issuer object or reserved names; for example, 'Self' or 'Unknown'.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Certificate type as supported by the provider (optional); for example 'OV-SSL', 'EV-SSL'
    #[serde(rename = "cty", skip_serializing_if = "Option::is_none")]
    pub cty: Option<String>,
    /// Indicates if the certificates generated under this policy should be published to certificate transparency logs.
    #[serde(rename = "cert_transparency", skip_serializing_if = "Option::is_none")]
    pub cert_transparency: Option<bool>,
}

impl IssuerParameters {
    /// Parameters for the issuer of the X509 component of a certificate.
    pub fn new() -> IssuerParameters {
        IssuerParameters {
            name: None,
            cty: None,
            cert_transparency: None,
        }
    }
}


