/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IssuerAttributes : The attributes of an issuer managed by the Key Vault service.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssuerAttributes {
    /// Determines whether the issuer is enabled.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Creation time in UTC.
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<i32>,
    /// Last updated time in UTC.
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<i32>,
}

impl IssuerAttributes {
    /// The attributes of an issuer managed by the Key Vault service.
    pub fn new() -> IssuerAttributes {
        IssuerAttributes {
            enabled: None,
            created: None,
            updated: None,
        }
    }
}


