/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// KeyVaultError : The key vault error exception.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeyVaultError {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<crate::models::Error>>,
}

impl KeyVaultError {
    /// The key vault error exception.
    pub fn new() -> KeyVaultError {
        KeyVaultError {
            error: None,
        }
    }
}


