/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// KeyUpdateParameters : The key update parameters.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeyUpdateParameters {
    /// Json web key operations. For more information on possible key operations, see JsonWebKeyOperation.
    #[serde(rename = "key_ops", skip_serializing_if = "Option::is_none")]
    pub key_ops: Option<Vec<KeyOps>>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::KeyAttributes>>,
    /// Application specific metadata in the form of key-value pairs.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<::std::collections::HashMap<String, String>>,
}

impl KeyUpdateParameters {
    /// The key update parameters.
    pub fn new() -> KeyUpdateParameters {
        KeyUpdateParameters {
            key_ops: None,
            attributes: None,
            tags: None,
        }
    }
}

/// Json web key operations. For more information on possible key operations, see JsonWebKeyOperation.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum KeyOps {
    #[serde(rename = "encrypt")]
    Encrypt,
    #[serde(rename = "decrypt")]
    Decrypt,
    #[serde(rename = "sign")]
    Sign,
    #[serde(rename = "verify")]
    Verify,
    #[serde(rename = "wrapKey")]
    WrapKey,
    #[serde(rename = "unwrapKey")]
    UnwrapKey,
    #[serde(rename = "import")]
    Import,
}

