/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LifetimeAction : Action and its trigger that will be performed by Key Vault over the lifetime of a certificate.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LifetimeAction {
    #[serde(rename = "trigger", skip_serializing_if = "Option::is_none")]
    pub trigger: Option<Box<crate::models::Trigger>>,
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<Box<crate::models::Action>>,
}

impl LifetimeAction {
    /// Action and its trigger that will be performed by Key Vault over the lifetime of a certificate.
    pub fn new() -> LifetimeAction {
        LifetimeAction {
            trigger: None,
            action: None,
        }
    }
}


