/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// OrganizationDetails : Details of the organization of the certificate issuer.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationDetails {
    /// Id of the organization.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Details of the organization administrator.
    #[serde(rename = "admin_details", skip_serializing_if = "Option::is_none")]
    pub admin_details: Option<Vec<crate::models::AdministratorDetails>>,
}

impl OrganizationDetails {
    /// Details of the organization of the certificate issuer.
    pub fn new() -> OrganizationDetails {
        OrganizationDetails {
            id: None,
            admin_details: None,
        }
    }
}


