/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Permission : Role definition permissions.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Permission {
    /// Action permissions that are granted.
    #[serde(rename = "actions", skip_serializing_if = "Option::is_none")]
    pub actions: Option<Vec<String>>,
    /// Action permissions that are excluded but not denied. They may be granted by other role definitions assigned to a principal.
    #[serde(rename = "notActions", skip_serializing_if = "Option::is_none")]
    pub not_actions: Option<Vec<String>>,
    /// Data action permissions that are granted.
    #[serde(rename = "dataActions", skip_serializing_if = "Option::is_none")]
    pub data_actions: Option<Vec<crate::models::DataAction>>,
    /// Data action permissions that are excluded but not denied. They may be granted by other role definitions assigned to a principal.
    #[serde(rename = "notDataActions", skip_serializing_if = "Option::is_none")]
    pub not_data_actions: Option<Vec<crate::models::DataAction>>,
}

impl Permission {
    /// Role definition permissions.
    pub fn new() -> Permission {
        Permission {
            actions: None,
            not_actions: None,
            data_actions: None,
            not_data_actions: None,
        }
    }
}


