/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RestoreOperationParameters {
    #[serde(rename = "sasTokenParameters")]
    pub sas_token_parameters: Box<crate::models::SasTokenParameter>,
    /// The Folder name of the blob where the previous successful full backup was stored
    #[serde(rename = "folderToRestore")]
    pub folder_to_restore: String,
}

impl RestoreOperationParameters {
    pub fn new(sas_token_parameters: crate::models::SasTokenParameter, folder_to_restore: String) -> RestoreOperationParameters {
        RestoreOperationParameters {
            sas_token_parameters: Box::new(sas_token_parameters),
            folder_to_restore,
        }
    }
}


