/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RoleAssignmentFilter : Role Assignments filter



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleAssignmentFilter {
    /// Returns role assignment of the specific principal.
    #[serde(rename = "principalId", skip_serializing_if = "Option::is_none")]
    pub principal_id: Option<String>,
}

impl RoleAssignmentFilter {
    /// Role Assignments filter
    pub fn new() -> RoleAssignmentFilter {
        RoleAssignmentFilter {
            principal_id: None,
        }
    }
}


