/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RoleDefinitionProperties : Role definition properties.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleDefinitionProperties {
    /// The role name.
    #[serde(rename = "roleName", skip_serializing_if = "Option::is_none")]
    pub role_name: Option<String>,
    /// The role definition description.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The role type.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<Type>,
    /// Role definition permissions.
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Vec<crate::models::Permission>>,
    /// Role definition assignable scopes.
    #[serde(rename = "assignableScopes", skip_serializing_if = "Option::is_none")]
    pub assignable_scopes: Option<Vec<crate::models::RoleScope>>,
}

impl RoleDefinitionProperties {
    /// Role definition properties.
    pub fn new() -> RoleDefinitionProperties {
        RoleDefinitionProperties {
            role_name: None,
            description: None,
            _type: None,
            permissions: None,
            assignable_scopes: None,
        }
    }
}

/// The role type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "AKVBuiltInRole")]
    AKVBuiltInRole,
    #[serde(rename = "CustomRole")]
    CustomRole,
}

