/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RoleScope : The role scope.

/// The role scope.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RoleScope {
    #[serde(rename = "/")]
    Slash,
    #[serde(rename = "/keys")]
    Keys,

}

impl ToString for RoleScope {
    fn to_string(&self) -> String {
        match self {
            Self::Slash => String::from("/"),
            Self::Keys => String::from("/keys"),
        }
    }
}




