/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RoleDefinitionCreateParameters : Role definition create parameters.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleDefinitionCreateParameters {
    #[serde(rename = "properties")]
    pub properties: Box<crate::models::RoleDefinitionProperties>,
}

impl RoleDefinitionCreateParameters {
    /// Role definition create parameters.
    pub fn new(properties: crate::models::RoleDefinitionProperties) -> RoleDefinitionCreateParameters {
        RoleDefinitionCreateParameters {
            properties: Box::new(properties),
        }
    }
}


