/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RoleAssignmentProperties : Role assignment properties.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleAssignmentProperties {
    /// The role definition ID used in the role assignment.
    #[serde(rename = "roleDefinitionId")]
    pub role_definition_id: String,
    /// The principal ID assigned to the role. This maps to the ID inside the Active Directory. It can point to a user, service principal, or security group.
    #[serde(rename = "principalId")]
    pub principal_id: String,
}

impl RoleAssignmentProperties {
    /// Role assignment properties.
    pub fn new(role_definition_id: String, principal_id: String) -> RoleAssignmentProperties {
        RoleAssignmentProperties {
            role_definition_id,
            principal_id,
        }
    }
}


