/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RoleDefinitionFilter : Role Definitions filter



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleDefinitionFilter {
    /// Returns role definition with the specific name.
    #[serde(rename = "roleName", skip_serializing_if = "Option::is_none")]
    pub role_name: Option<String>,
}

impl RoleDefinitionFilter {
    /// Role Definitions filter
    pub fn new() -> RoleDefinitionFilter {
        RoleDefinitionFilter {
            role_name: None,
        }
    }
}


