/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RoleAssignmentPropertiesWithScope : Role assignment properties with scope.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleAssignmentPropertiesWithScope {
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<crate::models::RoleScope>,
    /// The role definition ID.
    #[serde(rename = "roleDefinitionId", skip_serializing_if = "Option::is_none")]
    pub role_definition_id: Option<String>,
    /// The principal ID.
    #[serde(rename = "principalId", skip_serializing_if = "Option::is_none")]
    pub principal_id: Option<String>,
}

impl RoleAssignmentPropertiesWithScope {
    /// Role assignment properties with scope.
    pub fn new() -> RoleAssignmentPropertiesWithScope {
        RoleAssignmentPropertiesWithScope {
            scope: None,
            role_definition_id: None,
            principal_id: None,
        }
    }
}


