/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SasDefinitionUpdateParameters : The SAS definition update parameters.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SasDefinitionUpdateParameters {
    /// The SAS definition token template signed with an arbitrary key.  Tokens created according to the SAS definition will have the same properties as the template.
    #[serde(rename = "templateUri", skip_serializing_if = "Option::is_none")]
    pub template_uri: Option<String>,
    /// The type of SAS token the SAS definition will create.
    #[serde(rename = "sasType", skip_serializing_if = "Option::is_none")]
    pub sas_type: Option<SasType>,
    /// The validity period of SAS tokens created according to the SAS definition.
    #[serde(rename = "validityPeriod", skip_serializing_if = "Option::is_none")]
    pub validity_period: Option<String>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::SasDefinitionAttributes>>,
    /// Application specific metadata in the form of key-value pairs.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<::std::collections::HashMap<String, String>>,
}

impl SasDefinitionUpdateParameters {
    /// The SAS definition update parameters.
    pub fn new() -> SasDefinitionUpdateParameters {
        SasDefinitionUpdateParameters {
            template_uri: None,
            sas_type: None,
            validity_period: None,
            attributes: None,
            tags: None,
        }
    }
}

/// The type of SAS token the SAS definition will create.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SasType {
    #[serde(rename = "account")]
    Account,
    #[serde(rename = "service")]
    Service,
}

