/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SasTokenParameter {
    /// Azure Blob storage container Uri
    #[serde(rename = "storageResourceUri")]
    pub storage_resource_uri: String,
    /// The SAS token pointing to an Azure Blob storage container
    #[serde(rename = "token")]
    pub token: String,
}

impl SasTokenParameter {
    pub fn new(storage_resource_uri: String, token: String) -> SasTokenParameter {
        SasTokenParameter {
            storage_resource_uri,
            token,
        }
    }
}


