/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SasDefinitionCreateParameters : The SAS definition create parameters.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SasDefinitionCreateParameters {
    /// The SAS definition token template signed with an arbitrary key.  Tokens created according to the SAS definition will have the same properties as the template.
    #[serde(rename = "templateUri")]
    pub template_uri: String,
    /// The type of SAS token the SAS definition will create.
    #[serde(rename = "sasType")]
    pub sas_type: SasType,
    /// The validity period of SAS tokens created according to the SAS definition.
    #[serde(rename = "validityPeriod")]
    pub validity_period: String,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::SasDefinitionAttributes>>,
    /// Application specific metadata in the form of key-value pairs.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<::std::collections::HashMap<String, String>>,
}

impl SasDefinitionCreateParameters {
    /// The SAS definition create parameters.
    pub fn new(template_uri: String, sas_type: SasType, validity_period: String) -> SasDefinitionCreateParameters {
        SasDefinitionCreateParameters {
            template_uri,
            sas_type,
            validity_period,
            attributes: None,
            tags: None,
        }
    }
}

/// The type of SAS token the SAS definition will create.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SasType {
    #[serde(rename = "account")]
    Account,
    #[serde(rename = "service")]
    Service,
}

