/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SasDefinitionItem : The SAS definition item containing storage SAS definition metadata.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SasDefinitionItem {
    /// The storage SAS identifier.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The storage account SAS definition secret id.
    #[serde(rename = "sid", skip_serializing_if = "Option::is_none")]
    pub sid: Option<String>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::SasDefinitionAttributes>>,
    /// Application specific metadata in the form of key-value pairs.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<::std::collections::HashMap<String, String>>,
}

impl SasDefinitionItem {
    /// The SAS definition item containing storage SAS definition metadata.
    pub fn new() -> SasDefinitionItem {
        SasDefinitionItem {
            id: None,
            sid: None,
            attributes: None,
            tags: None,
        }
    }
}


