/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SecretUpdateParameters : The secret update parameters.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretUpdateParameters {
    /// Type of the secret value such as a password.
    #[serde(rename = "contentType", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::SecretAttributes>>,
    /// Application specific metadata in the form of key-value pairs.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<::std::collections::HashMap<String, String>>,
}

impl SecretUpdateParameters {
    /// The secret update parameters.
    pub fn new() -> SecretUpdateParameters {
        SecretUpdateParameters {
            content_type: None,
            attributes: None,
            tags: None,
        }
    }
}


