/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SecretItem : The secret item containing secret metadata.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretItem {
    /// Secret identifier.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::SecretAttributes>>,
    /// Application specific metadata in the form of key-value pairs.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<::std::collections::HashMap<String, String>>,
    /// Type of the secret value such as a password.
    #[serde(rename = "contentType", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    /// True if the secret's lifetime is managed by key vault. If this is a key backing a certificate, then managed will be true.
    #[serde(rename = "managed", skip_serializing_if = "Option::is_none")]
    pub managed: Option<bool>,
}

impl SecretItem {
    /// The secret item containing secret metadata.
    pub fn new() -> SecretItem {
        SecretItem {
            id: None,
            attributes: None,
            tags: None,
            content_type: None,
            managed: None,
        }
    }
}


