/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SecretBundle : A secret consisting of a value, id and its attributes.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretBundle {
    /// The secret value.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// The secret id.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The content type of the secret.
    #[serde(rename = "contentType", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::SecretAttributes>>,
    /// Application specific metadata in the form of key-value pairs.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<::std::collections::HashMap<String, String>>,
    /// If this is a secret backing a KV certificate, then this field specifies the corresponding key backing the KV certificate.
    #[serde(rename = "kid", skip_serializing_if = "Option::is_none")]
    pub kid: Option<String>,
    /// True if the secret's lifetime is managed by key vault. If this is a secret backing a certificate, then managed will be true.
    #[serde(rename = "managed", skip_serializing_if = "Option::is_none")]
    pub managed: Option<bool>,
}

impl SecretBundle {
    /// A secret consisting of a value, id and its attributes.
    pub fn new() -> SecretBundle {
        SecretBundle {
            value: None,
            id: None,
            content_type: None,
            attributes: None,
            tags: None,
            kid: None,
            managed: None,
        }
    }
}


