/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecurityDomainOperationStatus {
    /// operation status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "status_details", skip_serializing_if = "Option::is_none")]
    pub status_details: Option<String>,
}

impl SecurityDomainOperationStatus {
    pub fn new() -> SecurityDomainOperationStatus {
        SecurityDomainOperationStatus {
            status: None,
            status_details: None,
        }
    }
}

/// operation status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "Success")]
    Success,
    #[serde(rename = "InProgress")]
    InProgress,
    #[serde(rename = "Failed")]
    Failed,
}

