/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecurityDomainCertificateItem {
    #[serde(rename = "value")]
    pub value: Box<crate::models::SecurityDomainJsonWebKey>,
}

impl SecurityDomainCertificateItem {
    pub fn new(value: crate::models::SecurityDomainJsonWebKey) -> SecurityDomainCertificateItem {
        SecurityDomainCertificateItem {
            value: Box::new(value),
        }
    }
}


