/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SecurityDomainObject : The Security Domain.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecurityDomainObject {
    /// The Security Domain.
    #[serde(rename = "value")]
    pub value: String,
}

impl SecurityDomainObject {
    /// The Security Domain.
    pub fn new(value: String) -> SecurityDomainObject {
        SecurityDomainObject {
            value,
        }
    }
}


