/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// StorageAccountRegenerteKeyParameters : The storage account key regenerate parameters.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StorageAccountRegenerteKeyParameters {
    /// The storage account key name.
    #[serde(rename = "keyName")]
    pub key_name: String,
}

impl StorageAccountRegenerteKeyParameters {
    /// The storage account key regenerate parameters.
    pub fn new(key_name: String) -> StorageAccountRegenerteKeyParameters {
        StorageAccountRegenerteKeyParameters {
            key_name,
        }
    }
}


