/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// StorageAccountCreateParameters : The storage account create parameters.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StorageAccountCreateParameters {
    /// Storage account resource id.
    #[serde(rename = "resourceId")]
    pub resource_id: String,
    /// Current active storage account key name.
    #[serde(rename = "activeKeyName")]
    pub active_key_name: String,
    /// whether keyvault should manage the storage account for the user.
    #[serde(rename = "autoRegenerateKey")]
    pub auto_regenerate_key: bool,
    /// The key regeneration time duration specified in ISO-8601 format.
    #[serde(rename = "regenerationPeriod", skip_serializing_if = "Option::is_none")]
    pub regeneration_period: Option<String>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::StorageAccountAttributes>>,
    /// Application specific metadata in the form of key-value pairs.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<::std::collections::HashMap<String, String>>,
}

impl StorageAccountCreateParameters {
    /// The storage account create parameters.
    pub fn new(resource_id: String, active_key_name: String, auto_regenerate_key: bool) -> StorageAccountCreateParameters {
        StorageAccountCreateParameters {
            resource_id,
            active_key_name,
            auto_regenerate_key,
            regeneration_period: None,
            attributes: None,
            tags: None,
        }
    }
}


