/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SubjectAlternativeNames : The subject alternate names of a X509 object.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubjectAlternativeNames {
    /// Email addresses.
    #[serde(rename = "emails", skip_serializing_if = "Option::is_none")]
    pub emails: Option<Vec<String>>,
    /// Domain names.
    #[serde(rename = "dns_names", skip_serializing_if = "Option::is_none")]
    pub dns_names: Option<Vec<String>>,
    /// User principal names.
    #[serde(rename = "upns", skip_serializing_if = "Option::is_none")]
    pub upns: Option<Vec<String>>,
}

impl SubjectAlternativeNames {
    /// The subject alternate names of a X509 object.
    pub fn new() -> SubjectAlternativeNames {
        SubjectAlternativeNames {
            emails: None,
            dns_names: None,
            upns: None,
        }
    }
}


