/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferKey {
    /// Specifies the format of the transfer key
    #[serde(rename = "key_format", skip_serializing_if = "Option::is_none")]
    pub key_format: Option<String>,
    #[serde(rename = "transfer_key")]
    pub transfer_key: Box<crate::models::SecurityDomainJsonWebKey>,
}

impl TransferKey {
    pub fn new(transfer_key: crate::models::SecurityDomainJsonWebKey) -> TransferKey {
        TransferKey {
            key_format: None,
            transfer_key: Box::new(transfer_key),
        }
    }
}


