/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Trigger : A condition to be satisfied for an action to be executed.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Trigger {
    /// Percentage of lifetime at which to trigger. Value should be between 1 and 99.
    #[serde(rename = "lifetime_percentage", skip_serializing_if = "Option::is_none")]
    pub lifetime_percentage: Option<i32>,
    /// Days before expiry to attempt renewal. Value should be between 1 and validity_in_months multiplied by 27. If validity_in_months is 36, then value should be between 1 and 972 (36 * 27).
    #[serde(rename = "days_before_expiry", skip_serializing_if = "Option::is_none")]
    pub days_before_expiry: Option<i32>,
}

impl Trigger {
    /// A condition to be satisfied for an action to be executed.
    pub fn new() -> Trigger {
        Trigger {
            lifetime_percentage: None,
            days_before_expiry: None,
        }
    }
}


