/*
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * The version of the OpenAPI document: 7.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// X509CertificateProperties : Properties of the X509 component of a certificate.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct X509CertificateProperties {
    /// The subject name. Should be a valid X509 distinguished Name.
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    /// The enhanced key usage.
    #[serde(rename = "ekus", skip_serializing_if = "Option::is_none")]
    pub ekus: Option<Vec<String>>,
    #[serde(rename = "sans", skip_serializing_if = "Option::is_none")]
    pub sans: Option<Box<crate::models::SubjectAlternativeNames>>,
    /// List of key usages.
    #[serde(rename = "key_usage", skip_serializing_if = "Option::is_none")]
    pub key_usage: Option<Vec<KeyUsage>>,
    /// The duration that the certificate is valid in months.
    #[serde(rename = "validity_months", skip_serializing_if = "Option::is_none")]
    pub validity_months: Option<i32>,
}

impl X509CertificateProperties {
    /// Properties of the X509 component of a certificate.
    pub fn new() -> X509CertificateProperties {
        X509CertificateProperties {
            subject: None,
            ekus: None,
            sans: None,
            key_usage: None,
            validity_months: None,
        }
    }
}

/// List of key usages.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum KeyUsage {
    #[serde(rename = "digitalSignature")]
    DigitalSignature,
    #[serde(rename = "nonRepudiation")]
    NonRepudiation,
    #[serde(rename = "keyEncipherment")]
    KeyEncipherment,
    #[serde(rename = "dataEncipherment")]
    DataEncipherment,
    #[serde(rename = "keyAgreement")]
    KeyAgreement,
    #[serde(rename = "keyCertSign")]
    KeyCertSign,
    #[serde(rename = "cRLSign")]
    CRLSign,
    #[serde(rename = "encipherOnly")]
    EncipherOnly,
    #[serde(rename = "decipherOnly")]
    DecipherOnly,
}

